### PR TITLE
Add key derivation / password hashing primitives.

### PR DESCRIPTION
**Pull request by klakplok**
Binds the password hashing Argon2i primitives.
Adds key derivation from human passwords for the various secret key instances.

Cf. https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html

### CODE REVIEW

**Comment by dsheets** [comment]
This appears to fix #16. I'll review it soon and release it in 0.6.0.

**Comment by dsheets** [comment]
I've reviewed your patch and pushed some changes to your branch. Please let me know what you think and, if things are copacetic, I can publish 0.6.0 containing this functionality ASAP. Thanks, again!

**Comment by klakplok** [comment]
I'm fine with your changes, and thanks for fixing the few typos :).
I believe you can merge. I can also squash the refactoring commit before merging if you want.

Also, if that's ok, I'd like to submit two patches before the release (I was waiting for this review to adapt my coding style for the rest if necessary). One is very small (just a few constants to export), the other one is the one we discussed about the representation of secrets.

**Comment by dsheets** [comment]
Sounds good to me. No rebase necessary. Thanks for your contribution and I look forward to your patches!

**Pull request merged**
